website/views/bus.py
from flask import Blueprint, render_template, request, jsonify, g
from flask.ext.login import current_user
import requests
import json
from datetime import datetime
from models.stop import Stop
from models.service import Service
from models.associations import StopService
from models.vehicle import Vehicle
from models.update import update_table_date
from models.associations import UserService
from models.update import *
from database import db_session
from constants import *

# View responsible for requests which use/modify bus related models: Map, Updates
bus = Blueprint('bus', __name__)


# GET request to load Map with all services to choose from
@bus.route('/map')
def map_page():

    # Check if we need to update the services table
    is_update_needed = check_if_need_update("service", datetime.now(), SERVICES_UPDATE_RATE)
    if is_update_needed:
        update_services_stops()

    # Get all service numbers
    service_names = db_session.query(Service.name).all()
    favourites_array = []
    no_favourites = True

    if not current_user.is_anonymous():
        q = db_session.query(UserService, Service)
        favourites_assoc = q.filter(UserService.user_id == g.user.id).filter(Service.id == UserService.service_id).all()

        # Create array of serialised objects
        for favourite in favourites_assoc:
            favourites_array.append(favourite[1].name)

        if len(favourites_array) == 0:
            no_favourites = True
        else:
            no_favourites = False

    # Convert each name from unicode to string
    service_names_array = [service_name[0] for service_name in service_names]
    return render_template('pages/map.html', service_names=service_names_array, favourite_names= favourites_array, no_favourites=no_favourites)


# POST request to get all live vehicle data corresponding to the received services
# TODO: Add validation for request methods
@bus.route('/get/vehicles', methods=["POST"])
def get_vehicles():

    # Check if we need to update the vehicles table
    is_update_needed = check_if_need_update("vehicle", datetime.now(), VEHICLES_UPDATE_RATE)
    if is_update_needed:
        update_live_locations()

    # Get POST parameters
    service_numbers = request.form.getlist("services[]")

    # Make sure each service number is a string
    service_numbers = [str(service_number) for service_number in service_numbers]

    # Get all the vehicles whose service numbers are present in the input
    q = db_session.query(Vehicle)
    vehicles = q.filter(Vehicle.service_name.in_(service_numbers)).all()

    # Create array of serialised objects
    vehicles_array = []
    for vehicle in vehicles:
        vehicles_array.append(vehicle.as_dict())

    return jsonify(vehicles=vehicles_array)


# TODO: Add validation for request methods
@bus.route('/get/stop_names', methods=["POST"])
def get_stop_names():

    # Check if we need to update the services table
    is_update_needed = check_if_need_update("stop", datetime.now(), STOPS_UPDATE_RATE)
    if is_update_needed:
        update_services_stops()

    # Get POST parameter
    stop_str = str(request.form["stop_name"])

    # Get the name of all those stops which are starting with stop_str
    stop_names = Stop.query.with_entities(Stop.name).filter(Stop.name.like("%" + stop_str + "%")).all()
    stop_names = [stop[0] for stop in stop_names]

    return jsonify(stop_names=stop_names)


# TODO: Add validation for request methods
@bus.route('/get/route_and_stops', methods=["POST"])
def get_route_and_stops():

    # Check if we need to update the services table
    is_update_needed = check_if_need_update("stop", datetime.now(), STOPS_UPDATE_RATE)
    if is_update_needed:
        update_services_stops()

    # Get POST parameter
    service_name = str(request.form["service"])

    # Get all details of the selected service
    q = db_session.query(Service)
    service = q.filter(Service.name == service_name).all()

    if len(service) > 0:
        service = service[0]

        # Create array of serialised stop objects
        stop_array = []
        for stop in service.stops:
            stop_array.append(stop.as_dict())

        service = service.as_dict()
    else:
        service = {}

    return jsonify(service=service)


def delete_services_stops():

    # Delete existing data from stops, services and their linking table
    Service.query.delete()
    Stop.query.delete()
    StopService.query.delete()

    db_session.commit()
    db_session.flush()


@bus.route('/update')
def update_services_stops():

    # Delete all data first
    delete_services_stops()

    # Get services as json data
    json_data = requests.get(API_SERVICES, headers=API_HEADER)
    service_dict = json.loads(json_data.text)

    # Array of service objects
    services = service_dict["services"]

    # Get stops as json data
    json_data = requests.get(API_STOPS, headers=API_HEADER)
    stop_dict = json.loads(json_data.text)

    # Array of stop objects
    stops = stop_dict["stops"]

    # Update the tables' last_updated field
    service_date = datetime.fromtimestamp(int(service_dict["last_updated"]))
    update_table_date("service", service_date)
    stop_date = datetime.fromtimestamp(int(stop_dict["last_updated"]))
    update_table_date("stop", stop_date)

    # Create a service instance of each service and store them in a new dictionary
    service_dict = {}
    for service in services:
        new_service = Service()
        new_service.name = service["name"]
        new_service.service_type = service["service_type"]
        new_service.description = service["description"]
        new_service.route = json.dumps(service["routes"][0]["points"]) if len(service["routes"]) > 0 else "none"
        service_dict[service["name"]] = new_service
        db_session.add(new_service)

    # Create a stop instance of each stop and add corresponding services to them
    for stop in stops:
        new_stop = Stop()
        new_stop.name = stop["name"]
        new_stop.latitude = stop["latitude"]
        new_stop.longitude = stop["longitude"]

        # Add services to stops
        # Must take the set because sometimes the services are listed multiple times for a particular stop.
        stop_services = set(stop["services"])
        for service_name in stop_services:
            new_stop.services.append(service_dict[service_name])

        db_session.add(new_stop)

    db_session.commit()
    db_session.flush()


def update_live_locations():

    # Delete existing data from vehicles
    Vehicle.query.delete()

    # Get live vehicles as json data
    json_data = requests.get(API_VEHICLES, headers=API_HEADER)
    vehicle_dict = json.loads(json_data.text)

    # Array of service objects
    vehicles = vehicle_dict["vehicles"]

    # Update the vehicle table's last_updated field
    vehicles_date = datetime.fromtimestamp(int(vehicle_dict["last_updated"]))
    update_table_date("vehicle", vehicles_date)

    # Create a vehicle instance of each vehicle.
    for vehicle in vehicles:
        new_vehicle = Vehicle()
        new_vehicle.vehicle_id = vehicle["vehicle_id"]
        new_vehicle.destination = vehicle["destination"]
        new_vehicle.speed = vehicle["speed"]
        new_vehicle.heading = vehicle["heading"]
        new_vehicle.latitude = vehicle["latitude"]
        new_vehicle.longitude = vehicle["longitude"]
        new_vehicle.service_name = vehicle["service_name"]

        db_session.add(new_vehicle)

    db_session.commit()
    db_session.flush()

website/views/home.py
from flask import Blueprint, render_template, redirect, url_for, session, request, flash, g
from flask.ext.login import current_user, login_user, logout_user, login_required
import requests
import json
from constants import *
from oauth import OAuthSignIn
from models.User import User
from database import db_session

# View responsible for rendering basic static pages not related to any models: Home page, About page, Login page
home = Blueprint('home', __name__)
# Home
@home.route('/home')
@home.route('/')
def home_page():
    return render_template("pages/home.html")


# About
@home.route('/about')
def about_page():
    return render_template("pages/about.html")


# Login
@home.route('/login')
def login_page():
    return render_template("pages/login.html")


# Authorisation
@home.route('/authorise/<provider>')
def oauth_authorise(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('home.home_page'))
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@home.route('/callback/<provider>')
def oauth_callback(provider):
    if not current_user.is_anonymous():
        return redirect(url_for('home.home_page'))
    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email = oauth.callback()
    if social_id is None:
        flash('Authentication failed.')
        return redirect(url_for('home.home_page'))
    user = db_session.query(User).filter_by(social_id=social_id).first()
    if not user:
        user = User(social_id=social_id, nickname=username, email=email)
        db_session.add(user)
        db_session.commit()
    login_user(user, True)
    return redirect(url_for('home.home_page'))


# Logout
@home.route('/logout')
def logout_page():
    logout_user()
    return redirect(url_for('home.home_page'))

website/views/user.py
from flask import Blueprint, jsonify, g
from flask_login import login_required
from database import db_session
from models.associations import UserService
from models.service import Service
from sqlalchemy import exc

# View responsible for requests which modify the user model: Registration, Favourites
user = Blueprint('user', __name__)

@user.route('/favourites/get', methods=["GET"])
@login_required
def get_favourites():

    q = db_session.query(UserService, Service)
    favourites_assoc = q.filter(UserService.user_id == g.user.id).filter(Service.id == UserService.service_id).all()

    # Create array of serialised objects
    favourites_array = []
    for favourite in favourites_assoc:
        favourites_array.append(favourite[1].name)

    return jsonify(favourites=favourites_array)

@user.route('/favourites/put/<string:service_name>', methods=["GET"])
@login_required
def add_favourite(service_name):

    q = db_session.query(Service)
    try:
        service = q.filter(Service.name == service_name).one()
    except exc.SQLAlchemyError:
        return "", 404  # NOT FOUND

    new_user_service = UserService()
    new_user_service.user_id = g.user.id
    new_user_service.service_id = service.id

    db_session.add(new_user_service)

    try:
        db_session.commit()
    except exc.IntegrityError:
        return "", 409  # CONFLICT

    db_session.flush()

    return "", 201  # CREATED

@user.route('/favourites/delete/<string:service_name>', methods=["GET"])
@login_required
def remove_favourite(service_name):

    q = db_session.query(Service)
    try:
        service = q.filter(Service.name == service_name).one()
    except exc.SQLAlchemyError:
        return "", 404  # NOT FOUND

    service_q = db_session.query(UserService)
    try:
        service_record = service_q.filter(UserService.service_id == service.id).filter(UserService.user_id == g.user.id).one()
    except exc.SQLAlchemyError:
        return "", 404  # NOT FOUND

    try:
        db_session.delete(service_record)
        db_session.commit()
        db_session.flush()
    except exc.InvalidRequestError:
        return "", 422  #  UNPROCESSABLE ENTITY

    return "", 202  # ACCEPTED

website/templates/pages/about.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="/static/css/about.css">
{% endblock %}

{% block body %}
    <h1>About the Team</h1>
    <div class="row">
        <div class="col-md-2"><img src="../static/images/profiles/sky.png"/></div>
        <div class="col-md-10">
            <h2 class="member-name">Sky Welch</h2>
            <p class="member-desc">Sky was the team leader for this project. They worked primarily on the backend, including integration and the favouriting system.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-2"><img src="../static/images/profiles/marton.png"/></div>
        <div class="col-md-10">
            <h2 class="member-name">Márton Széles</h2>
            <p class="member-desc">Márton worked on both the backend and the front-end. He worked on the project structure, the database schema, the test suite, the REST API, as well as event and map related Typescript.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2"><img src="../static/images/profiles/jamie.png"/></div>
        <div class="col-md-10">
            <h2 class="member-name">Jamie MacDonald</h2>
            <p class="member-desc">Jamie worked on the layout, UX and design of the site. He added transparency in random locations and after 2 solid days of CSS has become firm friends with the Chrome Inspector.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-2"><img src="../static/images/profiles/joseph.png"/></div>
        <div class="col-md-10">
            <h2 class="member-name">Joseph Kennelly</h2>
            <p class="member-desc">Joseph worked on the front end. He worked on improving UI and front-end features.</p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-2"><img src="../static/images/profiles/richboy.png"/></div>
        <div class="col-md-10">
            <h2 class="member-name">Richboy Kaycee David</h2>
            <p class="member-desc">Richboy basically worked on Typescript and some part of the UI. A few places on the map integration and also few Typescript-UI integration improvements.</p>
        </div>
    </div>
	
   <div class="row">
        <div class="col-md-2"><img src="../static/images/profiles/worf.png"/></div>
        <div class="col-md-10">
            <h2 class="member-name">Lieutenant Commander Worf, son of Mogh</h2>
            <p class="member-desc">Worf's in depth knowledge of TypeScript, CSS and the engineering behind a Klingon Bird of Prey proved invaluable to our team during the construction of the website.</p>
        </div>
    </div>

    <p></p>
    </br>
    <script>
        $('#about_menu').addClass('active');
    </script>
{% endblock %}

website/templates/pages/account_settings.html
{% extends "base.html" %}

{% block body %}
    <h1>Account settings page</h1>
    <p>Some account settings stuff.</p>
{% endblock %}

website/templates/pages/home.html
{% extends "base.html" %}

{% block body %}
    <div class="header">
        <div class="header-foreground"></div>
        <div class="header-background"></div>
    </div>
    <div class="row" >
        <div class="col-lg-12">
            <h2>Our Features</h2>
             <p>The Transport for Klingons website uses the TfK API provided by the Klingon Empire. It allows users to track buses across Edinburgh to aid you in your galactic conquest or commute to work.</p>
            <h2>Future Updates</h2>
            <p>We hope to add support for Bird of Prey tracking in a future update.</p>
             <br><br>
         </div>
    </div>
    <h5>Copyright © Team Klingon 2015</h5>

	<script>
        $('#home_menu').addClass('active');
    </script>
{% endblock %}

website/templates/pages/login.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="/static/css/login.css">
{% endblock %}

{% block body %}

{% for message in get_flashed_messages() %}
    <p><b>Error</b>: {{ message }}</p>
{% endfor %}
{% if current_user.is_authenticated() %}
    <h2>Hi, {{ current_user.nickname }}!</h2>
    <p><a href="{{ url_for('home.logout_page') }}">Logout</a></p>
{% else %}

	<div class="oauth-container">
		<h2>Log in</h2>
		<a href="{{ url_for('home.oauth_authorise', provider='facebook') }}">
			<img class="social-btn" src="../static/images/logos/facebook_btn.png" width="250" height="50"/>
		</a>
		<br/>
		<a href="{{ url_for('home.oauth_authorise', provider='twitter') }}">
			<img class="social-btn" src="../static/images/logos/twitter_btn.png" width="250" height="50"/>
		</a>
	</div>

        

{% endif %}

{% endblock %}

website/templates/pages/map.html
{% extends "base.html" %}

{%  block head %}
    <script src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script type="text/javascript" src="/static/js/App.js"></script>
    <script type="text/javascript" src="/static/js/Runtime.js"></script>
    <link rel="stylesheet" href="/static/css/mapstyle.css">
{% endblock %}

{% block body %}
    <div class="col-sm-8" id="map-canvas"></div>
	
    <div class="col-sm-4" id="service-container" align="center">

        <div class="counter">
	    	<div id="countdown" style="display:none"></div>
        </div>

        <!-- if logged in AND favourites exist -->
        {% if g.user.is_authenticated() %}
            {% if not no_favourite %}
            	{% if favourite_names|length != 0 %}
                	<!-- show favourites -->
                	<p id="service-title">Favourites</p>
				
	                {% for service_name in favourite_names %}
	                    <div class="service-box" data-service="{{ service_name }}">
	                            {{ service_name }}
	                    </div>
	                {% endfor %}
	            {% endif %}
            {% endif %}

            <p id="service-title">Edit Favourites:</p>
            
            <div id="favAdd-box" class="favourite-box" title="Add to Favourite">+</div>

            <div id="favRmv-box" class="favourite-box" title="Remove from Favourite">-</div>
            <!-- <p>For Current Selection</p>  -->

        {% else %}
        {% endif %}

        <p id="service-title">Service</p>
        {% for service_name in service_names %}
            <div class="service-box" data-service="{{ service_name }}">
                {{ service_name }}
            </div>
        {% endfor %}
    </div>
	
	<div id="error_div" style="display:none"></div>

    <script>
        MapModule.init("{{ url_for('bus.get_route_and_stops') }}", "{{ url_for('bus.get_vehicles') }}", "{{ url_for('user.add_favourite', service_name='') }}", "{{ url_for('user.remove_favourite', service_name='') }}");
    	$('#map_menu').addClass('active');
    </script>
{% endblock %}